--CRIANDO TABELA DE PERFIL DE VAGA E ADICIONANDO OS PERFIS
CREATE TABLE Perfil_Usuario(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Tipo VARCHAR(50) NOT NULL
);

INSERT INTO Perfil_Usuario
VALUES ('Adm');

INSERT INTO Perfil_Usuario
VALUES ('Candidato');

--CRIANDO TABELA DE PERFIL DE VAGA E ADICIONANDO OS PERFIS 
CREATE TABLE Perfil_Vaga(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Tipo VARCHAR(50) NOT NULL
);

INSERT INTO Perfil_Vaga
VALUES ('Clt');	

INSERT INTO Perfil_Vaga
VALUES ('Pj');	

INSERT INTO Perfil_Vaga
VALUES ('Freelancer');	


--CRIANDO TABELA DE USUARIOS 
CREATE TABLE Usuario (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	Telefone VARCHAR(50) NOT NULL,
	CPF VARCHAR(50) NOT NULL,
	Id_Perfil INT NOT NULL,
	FOREIGN KEY (Id_Perfil) REFERENCES Perfil_Usuario(Id)
);

--ADICIONANDO USUARIO ADMIN PARA FIM DE TESTE
INSERT INTO Usuario
VALUES('Admin', 'Admin@gmail.com', '12345', '79999386209', '86158337536', 1);





--CRIANDO TABELA DE VAGA 
CREATE TABLE Vaga(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Descricao VARCHAR(MAX) NOT NULL,
	Id_Perfil INT NOT NULL,
	Valor DECIMAL NOT NULL,
	Ativa BIT DEFAULT 0,
	FOREIGN KEY (Id_Perfil) REFERENCES Perfil_Vaga(Id)
);


--CRIANDO TABELA DE CANDIDATURA 
CREATE TABLE Candidaturas(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Id_Usuario INT NOT NULL,
	Id_Vaga INT NOT NULL,
	FOREIGN KEY (Id_Usuario) REFERENCES Usuario(Id),
	FOREIGN KEY (Id_Vaga) REFERENCES Vaga(Id)
);























